# Generated by Django 2.1.3 on 2018-11-26 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start_dt', models.DateTimeField()),
                ('work_end_dt', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_employee', to='api.Company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveSmallIntegerField()),
                ('month', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='salary',
            name='company_employee',
            field=models.ForeignKey(default=1,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='api.CompanyEmployee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='work_end_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='work_end_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='work_start_dt',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='api.Person'),
        ),
        migrations.CreateModel(
            name='SalaryCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('salary', models.PositiveSmallIntegerField()),
                ('employee',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='api.Person')),
            ],
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salarycache',
            name='salary',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
