# Generated by Django 2.1.3 on 2018-12-10 10:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start_dt', models.DateField()),
                ('work_end_dt', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_employee', to='api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('company_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CompanyEmployee')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2018)])),
                ('salary', models.PositiveSmallIntegerField(null=True)),
                ('company_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CompanyEmployee')),
            ],
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='salarycache',
            unique_together={('company_employee', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('company_employee', 'date')},
        ),
        migrations.AlterField(
            model_name='salarycache',
            name='year',
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(2000)]),
        ),
    ]
