# Generated by Django 2.1.3 on 2018-12-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('company_employee', 'date')},
        ),
    ]
