# Generated by Django 2.1.3 on 2018-11-26 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='company_employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.CompanyEmployee'),
            preserve_default=False,
        ),
    ]
