# Generated by Django 2.1.3 on 2018-12-11 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181210_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarycache',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2068)]),
        ),
    ]
