# Generated by Django 2.1.3 on 2018-11-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_salary_company_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployee',
            name='work_end_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
