# Generated by Django 2.1.3 on 2018-11-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181126_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployee',
            name='work_end_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='work_start_dt',
            field=models.DateField(),
        ),
    ]
