# Generated by Django 2.1.3 on 2018-11-26 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181126_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person'),
        ),
    ]
