# Generated by Django 2.1.3 on 2018-12-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_salarycache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='salary',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
