# Generated by Django 2.1.3 on 2018-12-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181205_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='salary',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
