# Generated by Django 2.1.3 on 2018-12-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181205_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='salary',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salarycache',
            name='salary',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
