# Generated by Django 2.1.3 on 2018-12-05 05:31

from django.contrib.auth.models import User
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181205_0530'),
    ]

    try:
        superuser = User.objects.create_superuser(
            username='admin',
            email='admin@mail.ru',
            password='adminadmin')

        superuser.save()
    except Exception as err:
        print('-'*50)
        print(err)
        print('-'*50)

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='salary',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salarycache',
            name='salary',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
