# Generated by Django 2.1.3 on 2018-12-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181205_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarycache',
            name='employee',
        ),
        migrations.DeleteModel(
            name='SalaryCache',
        ),
    ]
